### ISSUE TITLE
SW6.6 compatibility

### ISSUE THREAD

**Issue by JolanDeNef** [mailcampaigns/shopware-6-abandoned-cart-plugin#4]
The plugin is not yet compatible with Shopware 6.6.

Are you planning to support this in the near future?

Kind regards

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Hi Jolan,

You're lucky 😊🍀
It's included in our current sprint.

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Currently working on the [new branch](https://github.com/mailcampaigns/shopware-6-abandoned-cart-plugin/tree/shopware-6.6-upgrade) and it seems to do what it needs to. 
I'll test and probably release next week.

**Comment by m-a-x-s-e-e-l-i-g** [comment]
![image](https://github.com/user-attachments/assets/46c12ef3-cebc-4df1-8e7d-09a0c7253c34)

https://github.com/mailcampaigns/shopware-6-abandoned-cart-plugin/releases/tag/3.0.0
